[2025-03-06 11:27:23] [INFO    ] discord.client: logging in using static token
[2025-03-06 11:27:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2b808f6cbf1301b13bfa73346f6f4868).
[2025-03-06 11:27:47] [INFO    ] discord.voice_state: Connecting to voice...
[2025-03-06 11:27:47] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2025-03-06 11:27:47] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: us-central295.discord.media
[2025-03-06 11:27:47] [INFO    ] discord.voice_state: Voice connection complete.
[2025-03-06 11:28:54] [INFO    ] discord.player: ffmpeg process 125636 successfully terminated with return code of 0.
[2025-03-06 11:28:59] [INFO    ] discord.player: ffmpeg process 125641 successfully terminated with return code of 0.
[2025-03-06 11:29:04] [INFO    ] discord.player: ffmpeg process 125645 successfully terminated with return code of 0.
[2025-03-06 11:29:22] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1339030117430853708 (Guild ID 134415388233433089)
[2025-03-06 11:49:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 11:57:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 12:27:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 12:40:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 13:51:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 15:53:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 15:56:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 18:18:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 18:43:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 2b808f6cbf1301b13bfa73346f6f4868.
[2025-03-06 19:32:51] [INFO    ] discord.voice_state: Connecting to voice...
[2025-03-06 19:32:51] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2025-03-06 19:32:51] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: us-central8865.discord.media
[2025-03-06 19:32:51] [INFO    ] discord.voice_state: Voice connection complete.
Fatal (internal) error in silk/resampler.c, line 184: assertion failed: inLen >= S->Fs_in_kHz
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
Error closing file pipe:1: Broken pipe
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
Error closing file pipe:1: Broken pipe
Error writing trailer of pipe:1: Broken pipe
Error closing file pipe:1: Broken pipe
[2025-03-06 19:41:13] [INFO    ] discord.client: logging in using static token
[2025-03-06 19:41:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 82a15a5dfd363d1e90e1ad0f865937a6).
BOT AWAKE AND READY
Task exception was never retrieved
future: <Task finished name='discord.py: on_message' coro=<Client._run_event() done, defined at /home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/client.py:441> exception=SystemExit()>
Traceback (most recent call last):
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/lucassukeunkim/scuffed_discord_bot/bot.py", line 278, in on_message
    await bot.process_commands(message)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucassukeunkim/scuffed_discord_bot/bot.py", line 2071, in kys
    sys.exit()
SystemExit
[2025-03-06 20:59:33] [INFO    ] discord.client: logging in using static token
[2025-03-06 20:59:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0a93c686001a2c9d49118bbcec1b4cf8).
[2025-03-06 21:04:32] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/lucassukeunkim/scuffed_discord_bot/bot.py", line 2088, in <module>
    bot.run(BOT_TOKEN, reconnect=True)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/lucassukeunkim/scuffed_discord_bot/bot.py", line 278, in on_message
    await bot.process_commands(message)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/lucassukeunkim/myenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/lucassukeunkim/scuffed_discord_bot/bot.py", line 1758, in update
    result = subprocess.run(["git", "pull", "origin", "main"], capture_output=True, text=True)
  File "/usr/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

[2025-03-06 21:06:48] [INFO    ] discord.client: logging in using static token
[2025-03-06 21:06:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e5f1f7d8893d54e71d962cf15ad9c20c).
